### PR TITLE
feat: use anchor element for submission card

### LINKED ISSUE #111: Open in new window with middle click
Middle click which generally means "Open in New window" doesn't work

### PR DESCRIPTION
**Pull request by kdembler**
Resolves #111 

This PR makes the submission card render as a `a` element. This allows it to use browser-native navigation features like "Open in a new tab" and so on.

It also carries some drawbacks:
- The text on the card isn't selectable now (not a big deal I presume)
- `a > a` isn't a valid HTML, so since the card is `a` now, I've had to remove the Etherscan icon link from the footer.

I'd love to hear feedback on the Etherscan icon removal. I'd argue it wasn't very valuable in the card anyway since it was extremely hard to click on the card because of the hover translate effect. You can also be directed to Etherscan from the profile details.

As an alternative, I guess I could leave the logo in the footer but make it a `div` and do navigation programatically with JS, but don't see that as a great solution.

Let me know what you think!

### CODE REVIEW

**Comment by mtsalenc** [comment]
The pros outweigh the cons here. LGTM and if anyone complains we can put it back.

**Comment by kdembler** [comment]
@mtsalenc Sorry for asking here, but could you possibly [vouch for me on PoH](https://app.proofofhumanity.id/profile/0x45F2aBcE86a938Bb4d4633048dfA15bED7A5E310?network=mainnet)? 😅 If so, I'd happily reimburse you for the fees.

**Comment by mtsalenc** [comment]
Absolutely! You are the #1 human contributor outside the team :)

**Comment by kdembler** [comment]
That'd be really awesome! Also, when you have some spare time, I'd love to hear feedback on https://github.com/Proof-Of-Humanity/proof-of-humanity-web/issues/206, I could work on that

**Pull request merged**
