### PR TITLE
docs: improve contributor QOL with node version

### PR DESCRIPTION
**Pull request by justinkalland**
Update CONTRIBUTING.md with new troubleshooting section.

Add `.nvmrc` - this is important for contributors using [Node Version Manager](https://github.com/nvm-sh/nvm) (a standard best practice). Some cloud providers, build tools, and I believe IDEs also take advantage of this config.

Node 10 is what Netlify was already using (via `.node-version`)

### CODE REVIEW

**Comment by RoboTeddy** [comment]
(I ran into the same issue when getting my dev version up and running, so I appreciate this PR)

What follows is related but off-topic and wouldn't need to be resolved for this PR:

For what it's worth, the whole project seems to run fine on much newer versions of node as long as you install the latest version of `keccak` manually first — I suspect that an outdated version of `keccak` is being installed by one of the dependencies we list in package.json.

Node 10 reached end of life (no longer maintained even for security fixes) in April 2021. We should probably upgrade node. (I'm not sure which dep depends on it). If we're lucky, we might just be able to bump one version number in package.json and then have everything working on later versions of node.

`npm audit` may also be prudent, since a bunch of packages we depend on have since had security fixes.

**Comment by justinkalland** [comment]
Agree with @RoboTeddy , the package that uses `keccak` is [`web3`](https://www.npmjs.com/package/web3). Using Node 10 makes me weak me in the knees (as a server-side JS guy). From my searching it appears to be a common issue. I saw projects using Node 12 fine with `keccak` but it didn't for me. Maybe if I have time this week I will try and dig deeper. Someone recommended a `sudo npm i web3` but NPM makes me paranoid enough without throwing a sudo in front 🤣

**Comment by RoboTeddy** [comment]
you're right — `web3` does depend on `keccak`, but it seems to depend on a more recent version that works on later versions of node.

the culprit seems to be the `authereum` requirement, which seemingly depends on an old version of `keccak`. Upgrading `authereum` to its latest version doesn't seem to solve the problem.

One route could be:
(a) for the time-being, add the latest `keccak` directly as a dependency in our project, which solves the problem in effect, since it seems to satisfy `authereum` and prevents that project from trying to install its own old version,
(b) submit a change to the `authereum` project suggesting using the latest `keccak`; if it's ever included upstream, we can undo `(a)`.

**Comment by RoboTeddy** [comment]
Did a little more digging — I think the bad/old version of keccak is required in `package-lock.json` but not by anything currently listed in `package.json`. To fix, I cloned a clean version of the repository, ran `npm update keccak256`, and everything was fine on later versions of node. @justinkalland, I could make a PR with the resulting fixed `package-lock.json` if you'd like; I don't want to step on top of what you have going on in this branch though! Let me know what you'd like.

**Comment by justinkalland** [comment]
Your solution would be cleaner, are you on MacOS? Do you think it is because the underline module was already built on your machine (Python)?


I will try your solution on my machine with different node versions. I would still like to have a "target" version and .nvmrc though. Also Netlify is building with 10, that should be changed.

**Comment by RoboTeddy** [comment]
> Do you think it is because the underline module was already built on your machine (Python)?

I blew away `node_modules/` between each test, so it probably not

> I would still like to have a "target" version and .nvmrc though. Also Netlify is building with 10, that should be changed.

Agreed! If we update `package-lock.json` via `npm update keccak256`, then we may not need the troubleshooting doc section, and other folks will be able to get up and running more smoothly.

**Comment by justinkalland** [comment]
I can confirm, using `npm update keccak256` changes the package lock to use `keccak256 1.0.0` -> `1.0.2` and more importantly the dependency `keccak 1.4.0` -> `keccak 3.0.1`. 

After this update I was able to use Node all the way up to 16 (via clean clone, NVM on MacOS).

I am closing this PR because it is no longer needed. If you can create a PR with your fix @RoboTeddy I will support it, currently it a new contributor can't get started easily by following CONTRIBUTING.

Next will be deciding on a target version, both for `.nvmrc` and Netlify builds (currently pinned at 10 by `.node-version` - but I believe that can be a separate PR.

**Pull request closed without merging**
