### PR TITLE
Fixes Name Overflows by Breaking Anywhere

### PR DESCRIPTION
**Pull request by ferittuncer**
Before:
Screenshot from 2021-05-02 15-38-45

After: 
Screenshot from 2021-05-02 15-38-27

Also removed an Eslint rule that I don't understand what it's doing except preventing me to commit.

### CODE REVIEW

**Review by hbarcelos — APPROVED** [review]

**Review by hbarcelos — CHANGES_REQUESTED** [review]
There are some lint errors in the checks. Could you please fix those?

**Comment by ferittuncer** [comment]
I can't, there are 1001 of them. It's already out of control. 😅

**Comment by ferittuncer** [comment]
I'm sure I did not introduce linter errors, it's just 3 lines of code. 🤔

**Comment by hbarcelos** [comment]
Yeah, looks like the problem is on the `master` branch.

**Review by hbarcelos — APPROVED** [review]

**Pull request merged**
