### PR TITLE
Feat: added progress bar for photo and video upload

### PR DESCRIPTION
**Pull request by hbarcelos**
The way the submission for is designed, the photo and video upload doesn't start until the user press the submit button.
This is good to avoid useless files on our IPFS node, but the side-effect is that we show a spinner in the button for too much time and provide no other feedback for the user.

This PR updates the UI so we can have this:

poh-upload-progress

---

**Remarks:**

According to the [`fetch` spec](https://fetch.spec.whatwg.org/#fetch-api), it currently doesn't have a method for tracking request progress:

> The `fetch()` method is relatively low-level API for fetching resources. It covers slightly more ground than `XMLHttpRequest`, although it is currently lacking when it comes to request progression (not response progression).

That's why we have to fallback to the good ol' `XMLHttpRequest` object to be able to track the upload progress.

### CODE REVIEW

**Comment by hbarcelos** [comment]
Also, while this doesn't fix bugs like #171, it will provide users better feedback and help us debug.

**Comment by mtsalenc** [comment]
Is this ready for review?

**Comment by hbarcelos** [comment]
> Is this ready for review?

Yes.

**Review by ferittuncer — CHANGES_REQUESTED** [review]
I tried to submit a profile but submit button did not work. No perma spin, no error message but just nothing.

**Comment by mtsalenc** [comment]
> I tried to submit a profile but submit button did not work. No perma spin, no error message but just nothing.

It works for me.

**Comment by mtsalenc** [comment]
I've tested with MetaMask and Frame wallet. Both seem to be working so I will merge this.

**Comment by ferittuncer** [comment]
If it's not working for me, it won't be working for some others too. This merge will create more headaches in the future I think.

**Comment by hbarcelos** [comment]
@ferittuncer did the button look disabled (gray) or was it looking normal and doing nothing?
Were you running it locally?

**Comment by ferittuncer** [comment]
My bad, I forgot to fill mandatory display name field, that's why it was not working.

**Pull request merged**
