### PR TITLE
fix: avatar display size

### PR DESCRIPTION
**Pull request by spacecowb0y**
Currently avatars are being crop and display incorrectly, this small fix address this issue by changing the objectFit property to `cover`.

### CODE REVIEW

**Comment by alcercu** [comment]
Hello! The view is different in the card than in the profile view. Could you make it so that the pic is equally shown in both cases? Thanks a lot for your work! 🙌🏻 
image
image

**Review by 0x676f — CHANGES_REQUESTED** [review]
Your code change worked when opening a profile, e.g. https://deploy-preview-481--proof-of-humanity.netlify.app/profile/0x2160c9dcbe32edaa09834c97357104edaa13c1b3

But not in the _list_ of profiles: https://deploy-preview-481--proof-of-humanity.netlify.app/

**Comment by spacecowb0y** [comment]
Fixing it ASAP. I'll send a path soon.

**Review by 0x676f — APPROVED** [review]
Would it be possible to shape an uploaded image at the "Submit Profile" page as a circle as well? That way the person would get a more accurate _preview_ of what their photo would look like once submitted.

Screen Shot 2021-12-15 at 8 13 05 PM

**Comment by spacecowb0y** [comment]
Ha ha ha, at the end keeping the circular shape for all avatars it's kinda of tricky, some vertical images look cropped :(

**Comment by spacecowb0y** [comment]
This is the best I can make them look, using `object-position: "0 0"`.

Screen Shot 2021-12-15 at 19 45 51

**Comment by 0x676f** [comment]
@spacecowb0y Hmm, yes, this might cause problems for people vouching for new profiles. Good point.

Do you think we should add some sort of tool for helping people crop their uploaded images?

**Comment by spacecowb0y** [comment]
That could help, there are some client side tools for that. Also validating the dimensions of the images might help as well.

**Comment by 0x676f** [comment]
> That could help, there are some client side tools for that. Also validating the dimensions of the images might help as well.

@spacecowb0y Okay, could you create a new GitHub issue for that? And please put the relevant client-side tools in the issue description ☺

**Comment by bilinkis** [comment]
> @spacecowb0y Hmm, yes, this might cause problems for people vouching for new profiles. Good point.
> 
> Do you think we should add some sort of tool for helping people crop their uploaded images?

Currently working on this, as well as many other UI features. ETA a few weeks.

**Pull request closed without merging**
